### ISSUE TITLE
long form vs shortcut

### ISSUE THREAD

**Issue by rolinger** [EdwinHoksberg/php-fcm#8]
Finally got this working using the below:

```
$client = new \Fcm\FcmClient($serverKey, $senderId);
$subscribe = new \Fcm\Topic\Subscribe('my_topic_name');
$subscribe->addDevice($deviceId);
$client->send($subscribe);
```

However, no success using the shortcut, what am I doing wrong:
```
$client = new \Fcm\FcmClient($serverKey, $senderId);
// Shortcut function:
$client->topicSubscribe('my_topic_name', $deviceId);
```

**Comment by EdwinHoksberg** [comment]
Hey, that should be working fine, which error do you get?

**Comment by rolinger** [comment]
No error actually.  Just nothing happens.

$response = $client->topicSubscribe('topic',$devID) ;
print_r($response) ;

 just returns the whole object and the topic does not get registered (used a new topic just to ensure it would show up in FCM console.  Waited 10-15min...it never registered.  Then used long form method and topic registered immediately.

**Comment by EdwinHoksberg** [comment]
@rolinger, are you still experiencing this error?

**Comment by rolinger** [comment]
@EdwinHoksberg  - I still have the issue.  Saying its an error is misleading as nothing actually happens - which is weird.

**Comment by Kulltero** [comment]
this issue is a year old, but i'd like to point out 2 things:

1. when calling $client->topicSubscribe(), the second argument needs to be a string as the shorthand creates a Subscribtion instance that explicitly expects a string in its constructor (though this could be expanded to also allow arrays as the relevant function to add the deviceID does accept strings OR arrays).
2. calling $client->topicSubscribe(); only creates the subscription object, it doesnt actually get submitted unless you do $client->send($Subscription);

this wasnt clear to me at first either, as the documentation doesnt imply that topicSubscribe actually returns a needed instance.
@EdwinHoksberg perhaps this could be made more clear on the documentation, and perhaps the constructor for the shorthands can accept arrays where applicable

**Comment by AndyGaskell** [comment]
I'll try address this in...
 Improve documentation #39
